
export SOLR8_TOP_LEVEL_HOME="$HTRC_EF_PACKAGE_HOME/solr8"
export SOLR8_HOME="$SOLR8_TOP_LEVEL_HOME/server/solr"
#export SOLR8_PID_DIR="$SOLR8_HOME"

#export PATH="$SOLR8_TOP_LEVEL_HOME/bin:$PATH"



